### ISSUE TITLE
Question: attachToRecyclerView - custom animation possible?

### ISSUE THREAD

**Issue by Rainer-Lang** [jahirfiquitiva/FABsMenu#11]
How could I use/set different animations for hiding/showing the FAB?

**Comment by jahirfiquitiva** [comment]
It uses the default animations provided by `FloatingActionButton`.

You can get the `MenuFAB` object, using the `FABsMenu#getMenuButton()` method, and use it in your own implementation.

**Comment by Rainer-Lang** [comment]
Thanks
