### ISSUE TITLE
Only info

### ISSUE THREAD

**Issue by Rainer-Lang** [jahirfiquitiva/FABsMenu#12]
Do you know this lib? https://github.com/Clans/FloatingActionButton
It's not maintained anymore - but maybe there are features you could use.

**Comment by jahirfiquitiva** [comment]
Please list the features you'd like to see, and I'll try to do so. (Except custom animations)

**Comment by Rainer-Lang** [comment]
Is this possible?

1. Option to dim the FABsMenu background -> https://github.com/Clans/FloatingActionButton/raw/master/screenshots/menu_default_opened.png 
2. Option to add/remove button to the FABsMenu programmatically

**Comment by jahirfiquitiva** [comment]
@Rainer-Lang 

Both things are already available:

1. Use the `fabs_menu_overlayColor` attribute for `FABsMenuLayout`. The color is completely customizable.

2. Check the app sample code. I add and remove buttons programmatically there.

**Comment by Rainer-Lang** [comment]
Nothing for now. Thanks for your time. :heart_eyes:
I close this issue tomorrow when I'm back at the pc.
