### ISSUE TITLE
Is there any way to change the overlay color

### ISSUE THREAD

**Issue by EmmanuelMess** [jahirfiquitiva/FABsMenu#13]
When the FAB expands the overlay is tinted black (we have something similar in AmazeFileManager), is there any way to deactivate it or change it's color?

**Comment by jahirfiquitiva** [comment]
Yes, it is possible to change its color.

Just use the `fabs_menu_overlayColor` for `FABsMenuLayout` as mentioned [here](https://github.com/jahirfiquitiva/FABsMenu#attributes-explanation)
