### ISSUE TITLE
Does the button change to "mini" when the screen width is 460dp or less?

### ISSUE THREAD

**Issue by EmmanuelMess** [jahirfiquitiva/FABsMenu#14]
As per [Material Design Guidelines](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button).

**Comment by jahirfiquitiva** [comment]
I'm not sure if that happens. Haven't tested it in a device that small

Anyways, given that its dimension is in `dp` it should resize accordingly.

Please test it and let me know if it's good enough for you.

As a personal point of view:
I think that applies only when the button is "alone". i.e. when it's not being used as a menu. When used as a menu, there should be some distinction from the menu button and items buttons.

**Comment by EmmanuelMess** [comment]
The FAB doesn't change to mini on < 460dp.
<img height="350" src="https://user-images.githubusercontent.com/10991116/35159172-15a0260c-fd18-11e7-8878-14d46d5d1c83.png"/>

Ps: sorry for the absurdly late response.

**Comment by jahirfiquitiva** [comment]
@EmmanuelMess 

I personally don't like the idea of doing this. I know guidelines mention it, but they are not mentioning it for FABs Menus, so this might not apply in this case. The "menu" button should be distinguishable from the actual buttons.

Those are my thoughts, what do you think?

**Comment by EmmanuelMess** [comment]
I think there's a reason for the Material Guidelines saying it should be mini (maybe the normal button uses too large a percentage of the screen?). And I don't think it would look so bad.

**Comment by jahirfiquitiva** [comment]
I'll mark this as accepted but I won't really make it happen unless more people request it.

**Comment by G00fY2** [comment]
The default Google Calendar app uses a expandable FAB menu. Maybe we can use this as a reference.

@EmmanuelMess maybe you can check if Google itself is implementing this behavior correctly.

**Comment by EmmanuelMess** [comment]
Google is known for not following their standards...

**Comment by G00fY2** [comment]
Yeah that wouldn't be a surprise, true.

But I see @jahirfiquitiva 's argument about having distinct sizes for the main FAB and the submenu FABs.

**Comment by EmmanuelMess** [comment]
I am afraid that the fab might be too big in some screens.

**Comment by jahirfiquitiva** [comment]
@EmmanuelMess 
The FAB size is set in dp, which, if I'm not wrong, is a different dimension for every screen, which is also calculated by the screen dimensions.

Have you had reports or complaints, from real users, of the FAB being too big in certain screens?

**Comment by EmmanuelMess** [comment]
No I haven't, but reporting is reserved for crashes.

**Comment by jahirfiquitiva** [comment]
@EmmanuelMess 
Probably not. Check [this](https://stackoverflow.com/a/2025541/4864104)

**Comment by EmmanuelMess** [comment]
Okay, I'll do the maths (all measured in x axis):

Normal: 460dp width means that the fab ([56dp](https://material.io/guidelines/components/buttons-floating-action-button.html#)) plus the right margin ([16dp](https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-keylines-spacing)) is 72dp, 15% of the screen (max).

Mini: 460dp width means that the fab ([40dp](https://material.io/guidelines/components/buttons-floating-action-button.html#)) plus the right margin ([16dp](https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-keylines-spacing)) is 56dp, 12% of the screen (max).

Oh well, I suppose this can be closed...

**Comment by jahirfiquitiva** [comment]
Unfortunately, due to my limited time between work+University, I don't really find the way to provide proper support for this library. I really appreciate everyone that has been using it and that might continue using it, but, at least for now, this library is deprecated.

If you want to use a similar and more frequently updated library, please refer to @leinardi 's [FloatingActionSpeedDial](https://github.com/leinardi/FloatingActionButtonSpeedDial)

Thanks again for the amazing support. :raised_hands:
