### ISSUE TITLE
8 white pixels when coloring labels black

### ISSUE THREAD

**Issue by EmmanuelMess** [jahirfiquitiva/FABsMenu#16]
I am getting 8 white pixels when I color the labels black (on the corners):
<img height="175px" src="https://user-images.githubusercontent.com/10991116/33959790-6615f110-e027-11e7-94c8-8e7bcf6df675.png" /> <img height="175px" src="https://user-images.githubusercontent.com/10991116/33959874-a6e351ec-e027-11e7-8644-1af0f2864360.png" />
It's not the end of the world but I try to get the finished product as perfect as possible.

**Comment by jahirfiquitiva** [comment]
Hi @EmmanuelMess 
This could be an issue with android support libraries, would you mind updating to version `1.1.0` and testing? 
Thanks

**Comment by EmmanuelMess** [comment]
No, it doesn't fix it.

**Comment by jahirfiquitiva** [comment]
I'll leave this open but I can't work on a fix (if there is any) for now. Sorry

![bitmoji](https://render.bitstrips.com/v2/cpanel/dcbaa397-a792-45fa-8af9-8c55a26b5724-f1a30f5f-4907-483f-874a-54b05c8475ab-v1.png?transparent=1&palette=1&width=246)

**Comment by G00fY2** [comment]
I was able to reproduce this behavior in your sample app very easily: [	
reproduce label background issue](https://github.com/G00fY2/FABsMenu/commit/a4e57558c0cdb084ceddfd840e67bc9382249560)

Will try to look into this if I find some time.
