### ISSUE TITLE
Right to left layout breaks the button

### ISSUE THREAD

**Issue by EmmanuelMess** [jahirfiquitiva/FABsMenu#17]
Right to left layout breaks the button moves the button to the center.

**Comment by jahirfiquitiva** [comment]
Can you upload a screenshot, please?

**Comment by EmmanuelMess** [comment]
From AmazeFileManager app:
<img height="300px" src="https://user-images.githubusercontent.com/10991116/34346579-dee1c628-e9d7-11e7-9a27-bb998cbddf7e.png"/>

**Comment by jahirfiquitiva** [comment]
Can you upload one with the menu expanded?

**Comment by EmmanuelMess** [comment]
<img height="300px" src="https://user-images.githubusercontent.com/10991116/34346637-70c97cfc-e9d8-11e7-8022-7fa99eb0fb85.png"/>

**Comment by jahirfiquitiva** [comment]
@EmmanuelMess 
I think you will have to check if RTL is enabled and then change the position of the labels with `FABsMenu.setLabelsPositon()` method

Can you please try that?

**Comment by EmmanuelMess** [comment]
In 12hs, sorry.

**Comment by EmmanuelMess** [comment]
<img height="300px" src="https://user-images.githubusercontent.com/10991116/34366571-0fb3ac7c-ea7c-11e7-864b-028f56b55086.png"/>

**Comment by jahirfiquitiva** [comment]
Thanks for all the details and screenshots. I will do my best to manage to fix this soon, but I can't tell any ETA.

**Comment by EmmanuelMess** [comment]
Please detect RTL automatically.
