### ISSUE TITLE
AmazeFileManager should be using this lib by next release!

### ISSUE THREAD

**Issue by EmmanuelMess** [jahirfiquitiva/FABsMenu#18]
[AmazeFileManager](https://github.com/TeamAmaze/AmazeFileManager) should be using this lib by next release! It's already been pulled to master, but untill v3.3.0 it won't be in the published app.

**Comment by jahirfiquitiva** [comment]
That's really amazing! Thank you so much for using FABsMenu

![bitmoji](https://render.bitstrips.com/v2/cpanel/15f269e9-79ff-42f5-b6f8-df81e1cb3847-f1a30f5f-4907-483f-874a-54b05c8475ab-v1.png?transparent=1&palette=1&width=246)
