### ISSUE TITLE
First expand animation broken

### ISSUE THREAD

**Issue by Klabauterman** [jahirfiquitiva/FABsMenu#22]
It looks like on the first expand, the first frame shows the open menu and the the animation starts

**Comment by jahirfiquitiva** [comment]
Can you upload a video?

**Comment by Klabauterman** [comment]
Here is the video. If you play it in slow mode, you will see it. It appears only the first time I expand the menu. I also saw the "flickering" from my other ticket, which turned out not be be a flickering, but a selection state that seems to be triggered on all menu-buttons when the menu expands.

[20180109_105507_edited.mp4.zip](https://github.com/jahirfiquitiva/FABsMenu/files/1614653/20180109_105507_edited.mp4.zip)

**Comment by jahirfiquitiva** [comment]
@Klabauterman 

Thanks for the video. Would you mind creating a new issue with the new issue template and putting your 2 issues into the same one (since they are kinda related)

Thanks
