### ISSUE TITLE
Expand animation issues

### ISSUE THREAD

**Issue by Klabauterman** [jahirfiquitiva/FABsMenu#24]
The first time the FABsMenu expands the first frame shows the expanded menu instead of a collapsed menu, which makes it look like a flickering. (see video)

Clicking the main FAB triggers a selection animation of the expanding menu items. (see video)

https://github.com/jahirfiquitiva/FABsMenu/files/1614653/20180109_105507_edited.mp4.zip

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of FABsMenu.

###### Device/dashboard info:
 - FABsMenu version: 1.1.1
 - Device OS version: 7.0 Api Level 24
 - Device Manufacturer: Motorola
 - Device Name: G5

```java
<jahirfiquitiva.libs.fabsmenu.FABsMenuLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:fabs_menu_overlayColor="#00000000"
        app:fabs_menu_clickableOverlay="true"
        tools:layout_behavior="@string/fabs_menu_layout_behavior">

        <!-- FABs Menu is the main view. It will contain all the items FABs and it create the menu fab itself -->
        <jahirfiquitiva.libs.fabsmenu.FABsMenu
            android:id="@+id/fabs_menu"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|end"
            android:clipChildren="false"
            android:tint="@android:color/white"
            app:fab_menuMargins="16dp"
            app:fab_moreButtonPlusIcon="@drawable/add"
            app:fab_moreButtonBackgroundColor="@color/colorAccent"
            app:fab_moreButtonRippleColor="#fff"
            app:fab_moreButtonSize="normal"
            app:fab_labelsPosition="left"
            app:fab_expandDirection="up">

            <jahirfiquitiva.libs.fabsmenu.TitleFAB
                android:id="@+id/recipeCreateButton"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:srcCompat="@drawable/add"
                app:fab_title="@string/recipe_add_create"
                app:fab_enableTitleClick="true"
                app:fab_title_textColor="@color/colorAccent"
                app:rippleColor="#fff"
                app:fabSize="mini"
                app:backgroundTint="@color/colorAccent"/>

            <jahirfiquitiva.libs.fabsmenu.TitleFAB
                android:id="@+id/recipeImportButton"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:srcCompat="@drawable/import_export"
                app:fab_title="@string/recipe_add_import"
                app:fab_enableTitleClick="true"
                app:fab_title_textColor="@color/colorAccent"
                app:rippleColor="#fff"
                app:fabSize="mini"
                app:backgroundTint="@color/colorAccent"/>


        </jahirfiquitiva.libs.fabsmenu.FABsMenu>

    </jahirfiquitiva.libs.fabsmenu.FABsMenuLayout>
```

**Comment by jahirfiquitiva** [comment]
Thanks for the detailed report. I will look into it as soon as I can.

**Comment by G00fY2** [comment]
Not able to reproduce it on my Lollipop device and also not on my Pixel Android 8.1.
[device-2018-01-20-151908.zip](https://github.com/jahirfiquitiva/FABsMenu/files/1648876/device-2018-01-20-151908.zip)

@Klabauterman: Did you also see this issue running the sample app?

**Comment by Klabauterman** [comment]
I see the flickering of the titles in the example-app as well. But the other bug is not there. I moved the menu layout in may app from my fragment to the activity-layout and the first-animation-bug is gone as well.

**Comment by jahirfiquitiva** [comment]
Unfortunately, due to my limited time between work+University, I don't really find the way to provide proper support for this library. I really appreciate everyone that has been using it and that might continue using it, but, at least for now, this library is deprecated.

If you want to use a similar and more frequently updated library, please refer to @leinardi 's [FloatingActionSpeedDial](https://github.com/leinardi/FloatingActionButtonSpeedDial)

Thanks again for the amazing support. :raised_hands:
