### ISSUE TITLE
Add FABs Menu to AboutLibraries

### ISSUE THREAD

**Issue by EmmanuelMess** [jahirfiquitiva/FABsMenu#26]
> [AboutLibraries](https://github.com/mikepenz/AboutLibraries) is a library to offer some information of libraries. 

You should add yours to it's database (so that it can be picked up automagically).

**Comment by jahirfiquitiva** [comment]
@EmmanuelMess  I didn't saw your PR before, anyways, this should be fixed as of v `1.1.2`

![bitmoji](https://render.bitstrips.com/v2/cpanel/cf7648af-2035-4e07-9237-89aa82985b3c-f1a30f5f-4907-483f-874a-54b05c8475ab-v1.png?transparent=1&palette=1&width=246)
