### ISSUE TITLE
Is it possible to replicate the exact behavior of the FAB from "Inbox by Gmail" app?

### ISSUE THREAD

**Issue by leinardi** [jahirfiquitiva/FABsMenu#28]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of FABsMenu.

### Device/dashboard info:
 - FABsMenu version: NA
 - Android version: NA
 - Device Manufacturer: NA
 - Device Name: NA

### Reproduction Steps
NA

Is it currently possible to replicate the behavior of the "Inbox by Gmail" FAB with this library?

I am talking about this (please ignore the blue FAB in the left screenshot):

![image](https://i.stack.imgur.com/XUKoV.jpg)

In particular I am interested in:

1. (collapsed) Having an icon A and no label on the FAB (this should be possible already)
2. (clicked collapsed) Animate the expansion of the smaller FABs and the icon swap form A to B on the main FAB
3. (expanded) The background of the Activity is faded (this should be possible already) 
4. (expanded) The labels have a white background and grey text (this should be possible already)
5. (expanded) **The big FAB button, red in the screenshot, has its own label** 
6. (clicked expanded) It starts a custom action and is  toggling the FAB collapse.

**Comment by jahirfiquitiva** [comment]
So, to answer the things you are interested in:
1. 3. 4. Already available
2. It animates as the gif in README. But there can only be one icon with will be rotated on menu toggle.
5. 6. Not available right now. The main FAB is only used to expand/collapse the menu.
