### ISSUE TITLE
Attribute fabSize ignored: the TitleFABs are always mini

### ISSUE THREAD

**Issue by leinardi** [jahirfiquitiva/FABsMenu#30]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of FABsMenu.

### Device/dashboard info:
 - FABsMenu version: `1.1.2`
 - Android version: `API 16 to 27`
 - Device Manufacturer: `Google`
 - Device Name: `Emulator`

### Reproduction Steps

1. Build the sample app
2. Run it
3. Click on the FAB

### Expected Result
The green TitleFAB, since it has the `fab:fabSize="normal"` attribute set, should be as big as the MenuFAB.

### Actual Result
It is small as the other mini FABs.

![image](https://user-images.githubusercontent.com/273338/37842677-0b1c18e4-2ec3-11e8-852b-389f0f801df4.png)

**Comment by leinardi** [comment]
I made a PR that fixes this issue:
![image](https://user-images.githubusercontent.com/273338/37844405-f6baeed4-2ec7-11e8-8bb1-394cb43cc99f.png)

**Comment by jahirfiquitiva** [comment]
Fixed in v `1.1.3`
