### ISSUE TITLE
(BUG) The app gets crashes when I click the ADD button

### ISSUE THREAD

**Issue by friendsmobile** [jahirfiquitiva/FABsMenu#35]
# Project Information

* Repository: https://github.com/jahirfiquitiva/FABsMenu
* Project Name:  FABsMenu
* My Github Account: https://github.com/friendsmobile
* Download the application: [Here](https://github.com/jahirfiquitiva/FABsMenu/releases)

# Expected behavior

When I click the ADD button, the application should not crash, but a box should appear where I can add the link or icon.

# Actual behavior

The app gets crashes when I click the ADD button

# How to reproduce

* open the application
* click on ADD button
* Note the Error

* Browser/App version: 1.1.4
* Operating system: 6.0

# Recording Of The Bug

![20190609_163352](https://user-images.githubusercontent.com/51118734/59158525-2e57ff80-8a70-11e9-9e52-8db8be8db403.gif)

# Logcat

<pre><code>E/AndroidRuntime(20185): FATAL EXCEPTION: main

E/AndroidRuntime(20185): Process: jahirfiquitiva.apps.fabsmenu.demo, PID: 20185

E/AndroidRuntime(20185): java.lang.IllegalArgumentException: A floating action buttons menu should have no more than six options.

E/AndroidRuntime(20185): 	at jahirfiquitiva.libs.fabsmenu.FABsMenu.addButton(FABsMenu.java:273)

E/AndroidRuntime(20185): 	at jahirfiquitiva.libs.fabsmenu.FABsMenu.addButton(FABsMenu.java:286)

E/AndroidRuntime(20185): 	at jahirfiquitiva.apps.fabsmenu.demo.MainActivity.onOptionsItemSelected(MainActivity.java:148)

E/AndroidRuntime(20185): 	at android.app.Activity.onMenuItemSelected(Activity.java:3010)

E/AndroidRuntime(20185): 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:407)

E/AndroidRuntime(20185): 	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)

E/AndroidRuntime(20185): 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)

E/AndroidRuntime(20185): 	at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:674)

E/AndroidRuntime(20185): 	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)

E/AndroidRuntime(20185): 	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)

E/AndroidRuntime(20185): 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)

E/AndroidRuntime(20185): 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)

E/AndroidRuntime(20185): 	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)

E/AndroidRuntime(20185): 	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)

E/AndroidRuntime(20185): 	at android.view.View.performClick(View.java:5076)

E/AndroidRuntime(20185): 	at android.view.View$PerformClick.run(View.java:20279)

E/AndroidRuntime(20185): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(20185): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(20185): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(20185): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(20185): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(20185): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(20185): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(20185): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by friendsmobile** [comment]
okay sir next time i will follow the template  

thank you for feedback

**Comment by jahirfiquitiva** [comment]
please read the logs carefully before opening not actual issues

**A floating action buttons menu should have no more than six options.**
