### ISSUE TITLE
Allow any icon for menu fab

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/FABsMenu#5]
**Important:**
When menu is expanded the icon must be an X regardless of collapsed menu fab icon.

[Video of expected result](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B8v7jImPsDi-ajh6QTBYN05YVDg/components-buttons-fab-transition_speeddial_02.webm)

**Comment by Rainer-Lang** [comment]
+1

**Comment by percula** [comment]
I think we should implement vector drawable animation support instead. That way the start icon, end icon, and animation is completely up to devs. Animated icons can be created with the [ShapeShifter tool](https://shapeshifter.design/). Here are [some examples](https://www.androiddesignpatterns.com/2016/11/introduction-to-icon-animation-techniques.html).

When/if I get some free time I will try to submit a PR with this.

**Comment by jahirfiquitiva** [comment]
@percula 

Sounds like a really good idea. If you could help me with it, would be awesome too, as I'm too busy these weeks and don't think could make this happen.

![bitmoji](https://render.bitstrips.com/v2/cpanel/cf7648af-2035-4e07-9237-89aa82985b3c-f1a30f5f-4907-483f-874a-54b05c8475ab-v1.png?transparent=1&palette=1&width=246)

**Comment by rtchagas** [comment]
+1

**Comment by jahirfiquitiva** [comment]
Unfortunately, due to my limited time between work+University, I don't really find the way to provide proper support for this library. I really appreciate everyone that has been using it and that might continue using it, but, at least for now, this library is deprecated.

If you want to use a similar and more frequently updated library, please refer to @leinardi 's [FloatingActionSpeedDial](https://github.com/leinardi/FloatingActionButtonSpeedDial)

Thanks again for the amazing support. :raised_hands:
