### ISSUE TITLE
FAB not moved when snackbar is displayed

### ISSUE THREAD

**Issue by dashlabsdeveloper** [jahirfiquitiva/FABsMenu#8]
Default FAB in a CoordinatorLayout automatically detects when a snackbar is being displayed and moves itselft up and down. This behaviour isn't featured in FABsMenu currently

**Comment by jahirfiquitiva** [comment]
Thanks for the report @dashlabsdeveloper 

Do you have a sample project I can use to test this?

**Comment by jahirfiquitiva** [comment]
@dashlabsdeveloper 

Can you try this version `90f3fdc`?

Just, change it in your dependencies, like this:
```
    compile 'me.jahirfiquitiva:FABsMenu:90f3fdc'
```

And add [this line](https://github.com/jahirfiquitiva/FABsMenu/blob/snackbar-behavior/app/src/main/res/layout/activity_main.xml#L30) to your layout.

**Comment by jahirfiquitiva** [comment]
@dashlabsdeveloper 

Can you please this version `fdf2592`?

Just update it in your dependencies, like this:
```groovy
    compile 'me.jahirfiquitiva:FABsMenu:fdf2592'
```

And add [this](https://github.com/jahirfiquitiva/FABsMenu/blob/snackbar-behavior/app/src/main/res/layout/activity_main.xml#L21) and [this](https://github.com/jahirfiquitiva/FABsMenu/blob/snackbar-behavior/app/src/main/res/layout/activity_main.xml#L31) lines to your layout. Or check the new [sample layout](https://github.com/jahirfiquitiva/FABsMenu/blob/snackbar-behavior/app/src/main/res/layout/activity_main.xml)

**Comment by dashlabsdeveloper** [comment]
Now the behaviour is as expected. Thanks for the fast answer!

**Comment by jahirfiquitiva** [comment]
You can start using version `1.0.6`. Thanks for testing and using `FABsMenu` 😁
